/*
 * JOCL - Java bindings for OpenCL
 *
 * Copyright (c) 2009 Marco Hutter - http://www.jocl.org
 * 
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 * 
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jocl_CL */

#ifndef _Included_org_jocl_CL
#define _Included_org_jocl_CL
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jocl_CL_CL_CHAR_BIT
#define org_jocl_CL_CL_CHAR_BIT 8L
#undef org_jocl_CL_CL_SCHAR_MAX
#define org_jocl_CL_CL_SCHAR_MAX 127L
#undef org_jocl_CL_CL_SCHAR_MIN
#define org_jocl_CL_CL_SCHAR_MIN -128L
#undef org_jocl_CL_CL_CHAR_MAX
#define org_jocl_CL_CL_CHAR_MAX 127L
#undef org_jocl_CL_CL_CHAR_MIN
#define org_jocl_CL_CL_CHAR_MIN -128L
#undef org_jocl_CL_CL_UCHAR_MAX
#define org_jocl_CL_CL_UCHAR_MAX 255L
#undef org_jocl_CL_CL_SHRT_MAX
#define org_jocl_CL_CL_SHRT_MAX 32767L
#undef org_jocl_CL_CL_SHRT_MIN
#define org_jocl_CL_CL_SHRT_MIN -32768L
#undef org_jocl_CL_CL_USHRT_MAX
#define org_jocl_CL_CL_USHRT_MAX 65535L
#undef org_jocl_CL_CL_INT_MAX
#define org_jocl_CL_CL_INT_MAX 2147483647L
#undef org_jocl_CL_CL_INT_MIN
#define org_jocl_CL_CL_INT_MIN -2147483648L
#undef org_jocl_CL_CL_UINT_MAX
#define org_jocl_CL_CL_UINT_MAX -1i64
#undef org_jocl_CL_CL_LONG_MAX
#define org_jocl_CL_CL_LONG_MAX 9223372036854775807i64
#undef org_jocl_CL_CL_LONG_MIN
#define org_jocl_CL_CL_LONG_MIN -9223372036854775808i64
#undef org_jocl_CL_CL_ULONG_MAX
#define org_jocl_CL_CL_ULONG_MAX -1i64
#undef org_jocl_CL_CL_FLT_DIG
#define org_jocl_CL_CL_FLT_DIG 6L
#undef org_jocl_CL_CL_FLT_MANT_DIG
#define org_jocl_CL_CL_FLT_MANT_DIG 24L
#undef org_jocl_CL_CL_FLT_MAX_10_EXP
#define org_jocl_CL_CL_FLT_MAX_10_EXP 38L
#undef org_jocl_CL_CL_FLT_MAX_EXP
#define org_jocl_CL_CL_FLT_MAX_EXP 128L
#undef org_jocl_CL_CL_FLT_MIN_10_EXP
#define org_jocl_CL_CL_FLT_MIN_10_EXP -37L
#undef org_jocl_CL_CL_FLT_MIN_EXP
#define org_jocl_CL_CL_FLT_MIN_EXP -125L
#undef org_jocl_CL_CL_FLT_RADIX
#define org_jocl_CL_CL_FLT_RADIX 2L
#undef org_jocl_CL_CL_FLT_MAX
#define org_jocl_CL_CL_FLT_MAX 3.4028235E38f
#undef org_jocl_CL_CL_FLT_MIN
#define org_jocl_CL_CL_FLT_MIN 1.17549435E-38f
#undef org_jocl_CL_CL_FLT_EPSILON
#define org_jocl_CL_CL_FLT_EPSILON 1.1920929E-7f
#undef org_jocl_CL_CL_DBL_DIG
#define org_jocl_CL_CL_DBL_DIG 15L
#undef org_jocl_CL_CL_DBL_MANT_DIG
#define org_jocl_CL_CL_DBL_MANT_DIG 53L
#undef org_jocl_CL_CL_DBL_MAX_10_EXP
#define org_jocl_CL_CL_DBL_MAX_10_EXP 308L
#undef org_jocl_CL_CL_DBL_MAX_EXP
#define org_jocl_CL_CL_DBL_MAX_EXP 1024L
#undef org_jocl_CL_CL_DBL_MIN_10_EXP
#define org_jocl_CL_CL_DBL_MIN_10_EXP -307L
#undef org_jocl_CL_CL_DBL_MIN_EXP
#define org_jocl_CL_CL_DBL_MIN_EXP -1021L
#undef org_jocl_CL_CL_DBL_RADIX
#define org_jocl_CL_CL_DBL_RADIX 2L
#undef org_jocl_CL_CL_DBL_MAX
#define org_jocl_CL_CL_DBL_MAX 1.7976931348623157E308
#undef org_jocl_CL_CL_DBL_MIN
#define org_jocl_CL_CL_DBL_MIN 2.2250738585072014E-308
#undef org_jocl_CL_CL_DBL_EPSILON
#define org_jocl_CL_CL_DBL_EPSILON 2.220446049250313E-16
#undef org_jocl_CL_CL_SUCCESS
#define org_jocl_CL_CL_SUCCESS 0L
#undef org_jocl_CL_CL_DEVICE_NOT_FOUND
#define org_jocl_CL_CL_DEVICE_NOT_FOUND -1L
#undef org_jocl_CL_CL_DEVICE_NOT_AVAILABLE
#define org_jocl_CL_CL_DEVICE_NOT_AVAILABLE -2L
#undef org_jocl_CL_CL_COMPILER_NOT_AVAILABLE
#define org_jocl_CL_CL_COMPILER_NOT_AVAILABLE -3L
#undef org_jocl_CL_CL_MEM_OBJECT_ALLOCATION_FAILURE
#define org_jocl_CL_CL_MEM_OBJECT_ALLOCATION_FAILURE -4L
#undef org_jocl_CL_CL_OUT_OF_RESOURCES
#define org_jocl_CL_CL_OUT_OF_RESOURCES -5L
#undef org_jocl_CL_CL_OUT_OF_HOST_MEMORY
#define org_jocl_CL_CL_OUT_OF_HOST_MEMORY -6L
#undef org_jocl_CL_CL_PROFILING_INFO_NOT_AVAILABLE
#define org_jocl_CL_CL_PROFILING_INFO_NOT_AVAILABLE -7L
#undef org_jocl_CL_CL_MEM_COPY_OVERLAP
#define org_jocl_CL_CL_MEM_COPY_OVERLAP -8L
#undef org_jocl_CL_CL_IMAGE_FORMAT_MISMATCH
#define org_jocl_CL_CL_IMAGE_FORMAT_MISMATCH -9L
#undef org_jocl_CL_CL_IMAGE_FORMAT_NOT_SUPPORTED
#define org_jocl_CL_CL_IMAGE_FORMAT_NOT_SUPPORTED -10L
#undef org_jocl_CL_CL_BUILD_PROGRAM_FAILURE
#define org_jocl_CL_CL_BUILD_PROGRAM_FAILURE -11L
#undef org_jocl_CL_CL_MAP_FAILURE
#define org_jocl_CL_CL_MAP_FAILURE -12L
#undef org_jocl_CL_CL_MISALIGNED_SUB_BUFFER_OFFSET
#define org_jocl_CL_CL_MISALIGNED_SUB_BUFFER_OFFSET -13L
#undef org_jocl_CL_CL_EXEC_STATUS_ERROR_FOR_EVENTS_IN_WAIT_LIST
#define org_jocl_CL_CL_EXEC_STATUS_ERROR_FOR_EVENTS_IN_WAIT_LIST -14L
#undef org_jocl_CL_CL_INVALID_VALUE
#define org_jocl_CL_CL_INVALID_VALUE -30L
#undef org_jocl_CL_CL_INVALID_DEVICE_TYPE
#define org_jocl_CL_CL_INVALID_DEVICE_TYPE -31L
#undef org_jocl_CL_CL_INVALID_PLATFORM
#define org_jocl_CL_CL_INVALID_PLATFORM -32L
#undef org_jocl_CL_CL_INVALID_DEVICE
#define org_jocl_CL_CL_INVALID_DEVICE -33L
#undef org_jocl_CL_CL_INVALID_CONTEXT
#define org_jocl_CL_CL_INVALID_CONTEXT -34L
#undef org_jocl_CL_CL_INVALID_QUEUE_PROPERTIES
#define org_jocl_CL_CL_INVALID_QUEUE_PROPERTIES -35L
#undef org_jocl_CL_CL_INVALID_COMMAND_QUEUE
#define org_jocl_CL_CL_INVALID_COMMAND_QUEUE -36L
#undef org_jocl_CL_CL_INVALID_HOST_PTR
#define org_jocl_CL_CL_INVALID_HOST_PTR -37L
#undef org_jocl_CL_CL_INVALID_MEM_OBJECT
#define org_jocl_CL_CL_INVALID_MEM_OBJECT -38L
#undef org_jocl_CL_CL_INVALID_IMAGE_FORMAT_DESCRIPTOR
#define org_jocl_CL_CL_INVALID_IMAGE_FORMAT_DESCRIPTOR -39L
#undef org_jocl_CL_CL_INVALID_IMAGE_SIZE
#define org_jocl_CL_CL_INVALID_IMAGE_SIZE -40L
#undef org_jocl_CL_CL_INVALID_SAMPLER
#define org_jocl_CL_CL_INVALID_SAMPLER -41L
#undef org_jocl_CL_CL_INVALID_BINARY
#define org_jocl_CL_CL_INVALID_BINARY -42L
#undef org_jocl_CL_CL_INVALID_BUILD_OPTIONS
#define org_jocl_CL_CL_INVALID_BUILD_OPTIONS -43L
#undef org_jocl_CL_CL_INVALID_PROGRAM
#define org_jocl_CL_CL_INVALID_PROGRAM -44L
#undef org_jocl_CL_CL_INVALID_PROGRAM_EXECUTABLE
#define org_jocl_CL_CL_INVALID_PROGRAM_EXECUTABLE -45L
#undef org_jocl_CL_CL_INVALID_KERNEL_NAME
#define org_jocl_CL_CL_INVALID_KERNEL_NAME -46L
#undef org_jocl_CL_CL_INVALID_KERNEL_DEFINITION
#define org_jocl_CL_CL_INVALID_KERNEL_DEFINITION -47L
#undef org_jocl_CL_CL_INVALID_KERNEL
#define org_jocl_CL_CL_INVALID_KERNEL -48L
#undef org_jocl_CL_CL_INVALID_ARG_INDEX
#define org_jocl_CL_CL_INVALID_ARG_INDEX -49L
#undef org_jocl_CL_CL_INVALID_ARG_VALUE
#define org_jocl_CL_CL_INVALID_ARG_VALUE -50L
#undef org_jocl_CL_CL_INVALID_ARG_SIZE
#define org_jocl_CL_CL_INVALID_ARG_SIZE -51L
#undef org_jocl_CL_CL_INVALID_KERNEL_ARGS
#define org_jocl_CL_CL_INVALID_KERNEL_ARGS -52L
#undef org_jocl_CL_CL_INVALID_WORK_DIMENSION
#define org_jocl_CL_CL_INVALID_WORK_DIMENSION -53L
#undef org_jocl_CL_CL_INVALID_WORK_GROUP_SIZE
#define org_jocl_CL_CL_INVALID_WORK_GROUP_SIZE -54L
#undef org_jocl_CL_CL_INVALID_WORK_ITEM_SIZE
#define org_jocl_CL_CL_INVALID_WORK_ITEM_SIZE -55L
#undef org_jocl_CL_CL_INVALID_GLOBAL_OFFSET
#define org_jocl_CL_CL_INVALID_GLOBAL_OFFSET -56L
#undef org_jocl_CL_CL_INVALID_EVENT_WAIT_LIST
#define org_jocl_CL_CL_INVALID_EVENT_WAIT_LIST -57L
#undef org_jocl_CL_CL_INVALID_EVENT
#define org_jocl_CL_CL_INVALID_EVENT -58L
#undef org_jocl_CL_CL_INVALID_OPERATION
#define org_jocl_CL_CL_INVALID_OPERATION -59L
#undef org_jocl_CL_CL_INVALID_GL_OBJECT
#define org_jocl_CL_CL_INVALID_GL_OBJECT -60L
#undef org_jocl_CL_CL_INVALID_BUFFER_SIZE
#define org_jocl_CL_CL_INVALID_BUFFER_SIZE -61L
#undef org_jocl_CL_CL_INVALID_MIP_LEVEL
#define org_jocl_CL_CL_INVALID_MIP_LEVEL -62L
#undef org_jocl_CL_CL_INVALID_GLOBAL_WORK_SIZE
#define org_jocl_CL_CL_INVALID_GLOBAL_WORK_SIZE -63L
#undef org_jocl_CL_CL_JOCL_INTERNAL_ERROR
#define org_jocl_CL_CL_JOCL_INTERNAL_ERROR -64L
#undef org_jocl_CL_CL_INVALID_GL_SHAREGROUP_REFERENCE_KHR
#define org_jocl_CL_CL_INVALID_GL_SHAREGROUP_REFERENCE_KHR -1000L
#undef org_jocl_CL_CL_TRUE
#define org_jocl_CL_CL_TRUE 1L
#undef org_jocl_CL_CL_FALSE
#define org_jocl_CL_CL_FALSE 0L
#undef org_jocl_CL_CL_PLATFORM_PROFILE
#define org_jocl_CL_CL_PLATFORM_PROFILE 2304L
#undef org_jocl_CL_CL_PLATFORM_VERSION
#define org_jocl_CL_CL_PLATFORM_VERSION 2305L
#undef org_jocl_CL_CL_PLATFORM_NAME
#define org_jocl_CL_CL_PLATFORM_NAME 2306L
#undef org_jocl_CL_CL_PLATFORM_VENDOR
#define org_jocl_CL_CL_PLATFORM_VENDOR 2307L
#undef org_jocl_CL_CL_PLATFORM_EXTENSIONS
#define org_jocl_CL_CL_PLATFORM_EXTENSIONS 2308L
#undef org_jocl_CL_CL_DEVICE_TYPE_DEFAULT
#define org_jocl_CL_CL_DEVICE_TYPE_DEFAULT 1i64
#undef org_jocl_CL_CL_DEVICE_TYPE_CPU
#define org_jocl_CL_CL_DEVICE_TYPE_CPU 2i64
#undef org_jocl_CL_CL_DEVICE_TYPE_GPU
#define org_jocl_CL_CL_DEVICE_TYPE_GPU 4i64
#undef org_jocl_CL_CL_DEVICE_TYPE_ACCELERATOR
#define org_jocl_CL_CL_DEVICE_TYPE_ACCELERATOR 8i64
#undef org_jocl_CL_CL_DEVICE_TYPE_ALL
#define org_jocl_CL_CL_DEVICE_TYPE_ALL -1i64
#undef org_jocl_CL_CL_DEVICE_TYPE
#define org_jocl_CL_CL_DEVICE_TYPE 4096L
#undef org_jocl_CL_CL_DEVICE_VENDOR_ID
#define org_jocl_CL_CL_DEVICE_VENDOR_ID 4097L
#undef org_jocl_CL_CL_DEVICE_MAX_COMPUTE_UNITS
#define org_jocl_CL_CL_DEVICE_MAX_COMPUTE_UNITS 4098L
#undef org_jocl_CL_CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS
#define org_jocl_CL_CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS 4099L
#undef org_jocl_CL_CL_DEVICE_MAX_WORK_GROUP_SIZE
#define org_jocl_CL_CL_DEVICE_MAX_WORK_GROUP_SIZE 4100L
#undef org_jocl_CL_CL_DEVICE_MAX_WORK_ITEM_SIZES
#define org_jocl_CL_CL_DEVICE_MAX_WORK_ITEM_SIZES 4101L
#undef org_jocl_CL_CL_DEVICE_PREFERRED_VECTOR_WIDTH_CHAR
#define org_jocl_CL_CL_DEVICE_PREFERRED_VECTOR_WIDTH_CHAR 4102L
#undef org_jocl_CL_CL_DEVICE_PREFERRED_VECTOR_WIDTH_SHORT
#define org_jocl_CL_CL_DEVICE_PREFERRED_VECTOR_WIDTH_SHORT 4103L
#undef org_jocl_CL_CL_DEVICE_PREFERRED_VECTOR_WIDTH_INT
#define org_jocl_CL_CL_DEVICE_PREFERRED_VECTOR_WIDTH_INT 4104L
#undef org_jocl_CL_CL_DEVICE_PREFERRED_VECTOR_WIDTH_LONG
#define org_jocl_CL_CL_DEVICE_PREFERRED_VECTOR_WIDTH_LONG 4105L
#undef org_jocl_CL_CL_DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT
#define org_jocl_CL_CL_DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT 4106L
#undef org_jocl_CL_CL_DEVICE_PREFERRED_VECTOR_WIDTH_DOUBLE
#define org_jocl_CL_CL_DEVICE_PREFERRED_VECTOR_WIDTH_DOUBLE 4107L
#undef org_jocl_CL_CL_DEVICE_MAX_CLOCK_FREQUENCY
#define org_jocl_CL_CL_DEVICE_MAX_CLOCK_FREQUENCY 4108L
#undef org_jocl_CL_CL_DEVICE_ADDRESS_BITS
#define org_jocl_CL_CL_DEVICE_ADDRESS_BITS 4109L
#undef org_jocl_CL_CL_DEVICE_MAX_READ_IMAGE_ARGS
#define org_jocl_CL_CL_DEVICE_MAX_READ_IMAGE_ARGS 4110L
#undef org_jocl_CL_CL_DEVICE_MAX_WRITE_IMAGE_ARGS
#define org_jocl_CL_CL_DEVICE_MAX_WRITE_IMAGE_ARGS 4111L
#undef org_jocl_CL_CL_DEVICE_MAX_MEM_ALLOC_SIZE
#define org_jocl_CL_CL_DEVICE_MAX_MEM_ALLOC_SIZE 4112L
#undef org_jocl_CL_CL_DEVICE_IMAGE2D_MAX_WIDTH
#define org_jocl_CL_CL_DEVICE_IMAGE2D_MAX_WIDTH 4113L
#undef org_jocl_CL_CL_DEVICE_IMAGE2D_MAX_HEIGHT
#define org_jocl_CL_CL_DEVICE_IMAGE2D_MAX_HEIGHT 4114L
#undef org_jocl_CL_CL_DEVICE_IMAGE3D_MAX_WIDTH
#define org_jocl_CL_CL_DEVICE_IMAGE3D_MAX_WIDTH 4115L
#undef org_jocl_CL_CL_DEVICE_IMAGE3D_MAX_HEIGHT
#define org_jocl_CL_CL_DEVICE_IMAGE3D_MAX_HEIGHT 4116L
#undef org_jocl_CL_CL_DEVICE_IMAGE3D_MAX_DEPTH
#define org_jocl_CL_CL_DEVICE_IMAGE3D_MAX_DEPTH 4117L
#undef org_jocl_CL_CL_DEVICE_IMAGE_SUPPORT
#define org_jocl_CL_CL_DEVICE_IMAGE_SUPPORT 4118L
#undef org_jocl_CL_CL_DEVICE_MAX_PARAMETER_SIZE
#define org_jocl_CL_CL_DEVICE_MAX_PARAMETER_SIZE 4119L
#undef org_jocl_CL_CL_DEVICE_MAX_SAMPLERS
#define org_jocl_CL_CL_DEVICE_MAX_SAMPLERS 4120L
#undef org_jocl_CL_CL_DEVICE_MEM_BASE_ADDR_ALIGN
#define org_jocl_CL_CL_DEVICE_MEM_BASE_ADDR_ALIGN 4121L
#undef org_jocl_CL_CL_DEVICE_MIN_DATA_TYPE_ALIGN_SIZE
#define org_jocl_CL_CL_DEVICE_MIN_DATA_TYPE_ALIGN_SIZE 4122L
#undef org_jocl_CL_CL_DEVICE_SINGLE_FP_CONFIG
#define org_jocl_CL_CL_DEVICE_SINGLE_FP_CONFIG 4123L
#undef org_jocl_CL_CL_DEVICE_GLOBAL_MEM_CACHE_TYPE
#define org_jocl_CL_CL_DEVICE_GLOBAL_MEM_CACHE_TYPE 4124L
#undef org_jocl_CL_CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE
#define org_jocl_CL_CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE 4125L
#undef org_jocl_CL_CL_DEVICE_GLOBAL_MEM_CACHE_SIZE
#define org_jocl_CL_CL_DEVICE_GLOBAL_MEM_CACHE_SIZE 4126L
#undef org_jocl_CL_CL_DEVICE_GLOBAL_MEM_SIZE
#define org_jocl_CL_CL_DEVICE_GLOBAL_MEM_SIZE 4127L
#undef org_jocl_CL_CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE
#define org_jocl_CL_CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE 4128L
#undef org_jocl_CL_CL_DEVICE_MAX_CONSTANT_ARGS
#define org_jocl_CL_CL_DEVICE_MAX_CONSTANT_ARGS 4129L
#undef org_jocl_CL_CL_DEVICE_LOCAL_MEM_TYPE
#define org_jocl_CL_CL_DEVICE_LOCAL_MEM_TYPE 4130L
#undef org_jocl_CL_CL_DEVICE_LOCAL_MEM_SIZE
#define org_jocl_CL_CL_DEVICE_LOCAL_MEM_SIZE 4131L
#undef org_jocl_CL_CL_DEVICE_ERROR_CORRECTION_SUPPORT
#define org_jocl_CL_CL_DEVICE_ERROR_CORRECTION_SUPPORT 4132L
#undef org_jocl_CL_CL_DEVICE_PROFILING_TIMER_RESOLUTION
#define org_jocl_CL_CL_DEVICE_PROFILING_TIMER_RESOLUTION 4133L
#undef org_jocl_CL_CL_DEVICE_ENDIAN_LITTLE
#define org_jocl_CL_CL_DEVICE_ENDIAN_LITTLE 4134L
#undef org_jocl_CL_CL_DEVICE_AVAILABLE
#define org_jocl_CL_CL_DEVICE_AVAILABLE 4135L
#undef org_jocl_CL_CL_DEVICE_COMPILER_AVAILABLE
#define org_jocl_CL_CL_DEVICE_COMPILER_AVAILABLE 4136L
#undef org_jocl_CL_CL_DEVICE_EXECUTION_CAPABILITIES
#define org_jocl_CL_CL_DEVICE_EXECUTION_CAPABILITIES 4137L
#undef org_jocl_CL_CL_DEVICE_QUEUE_PROPERTIES
#define org_jocl_CL_CL_DEVICE_QUEUE_PROPERTIES 4138L
#undef org_jocl_CL_CL_DEVICE_NAME
#define org_jocl_CL_CL_DEVICE_NAME 4139L
#undef org_jocl_CL_CL_DEVICE_VENDOR
#define org_jocl_CL_CL_DEVICE_VENDOR 4140L
#undef org_jocl_CL_CL_DRIVER_VERSION
#define org_jocl_CL_CL_DRIVER_VERSION 4141L
#undef org_jocl_CL_CL_DEVICE_PROFILE
#define org_jocl_CL_CL_DEVICE_PROFILE 4142L
#undef org_jocl_CL_CL_DEVICE_VERSION
#define org_jocl_CL_CL_DEVICE_VERSION 4143L
#undef org_jocl_CL_CL_DEVICE_EXTENSIONS
#define org_jocl_CL_CL_DEVICE_EXTENSIONS 4144L
#undef org_jocl_CL_CL_DEVICE_PLATFORM
#define org_jocl_CL_CL_DEVICE_PLATFORM 4145L
#undef org_jocl_CL_CL_DEVICE_PREFERRED_VECTOR_WIDTH_HALF
#define org_jocl_CL_CL_DEVICE_PREFERRED_VECTOR_WIDTH_HALF 4148L
#undef org_jocl_CL_CL_DEVICE_HOST_UNIFIED_MEMORY
#define org_jocl_CL_CL_DEVICE_HOST_UNIFIED_MEMORY 4149L
#undef org_jocl_CL_CL_DEVICE_NATIVE_VECTOR_WIDTH_CHAR
#define org_jocl_CL_CL_DEVICE_NATIVE_VECTOR_WIDTH_CHAR 4150L
#undef org_jocl_CL_CL_DEVICE_NATIVE_VECTOR_WIDTH_SHORT
#define org_jocl_CL_CL_DEVICE_NATIVE_VECTOR_WIDTH_SHORT 4151L
#undef org_jocl_CL_CL_DEVICE_NATIVE_VECTOR_WIDTH_INT
#define org_jocl_CL_CL_DEVICE_NATIVE_VECTOR_WIDTH_INT 4152L
#undef org_jocl_CL_CL_DEVICE_NATIVE_VECTOR_WIDTH_LONG
#define org_jocl_CL_CL_DEVICE_NATIVE_VECTOR_WIDTH_LONG 4153L
#undef org_jocl_CL_CL_DEVICE_NATIVE_VECTOR_WIDTH_FLOAT
#define org_jocl_CL_CL_DEVICE_NATIVE_VECTOR_WIDTH_FLOAT 4154L
#undef org_jocl_CL_CL_DEVICE_NATIVE_VECTOR_WIDTH_DOUBLE
#define org_jocl_CL_CL_DEVICE_NATIVE_VECTOR_WIDTH_DOUBLE 4155L
#undef org_jocl_CL_CL_DEVICE_NATIVE_VECTOR_WIDTH_HALF
#define org_jocl_CL_CL_DEVICE_NATIVE_VECTOR_WIDTH_HALF 4156L
#undef org_jocl_CL_CL_DEVICE_OPENCL_C_VERSION
#define org_jocl_CL_CL_DEVICE_OPENCL_C_VERSION 4157L
#undef org_jocl_CL_CL_DEVICE_ADDRESS_32_BITS
#define org_jocl_CL_CL_DEVICE_ADDRESS_32_BITS 1i64
#undef org_jocl_CL_CL_DEVICE_ADDRESS_64_BITS
#define org_jocl_CL_CL_DEVICE_ADDRESS_64_BITS 2i64
#undef org_jocl_CL_CL_FP_DENORM
#define org_jocl_CL_CL_FP_DENORM 1i64
#undef org_jocl_CL_CL_FP_INF_NAN
#define org_jocl_CL_CL_FP_INF_NAN 2i64
#undef org_jocl_CL_CL_FP_ROUND_TO_NEAREST
#define org_jocl_CL_CL_FP_ROUND_TO_NEAREST 4i64
#undef org_jocl_CL_CL_FP_ROUND_TO_ZERO
#define org_jocl_CL_CL_FP_ROUND_TO_ZERO 8i64
#undef org_jocl_CL_CL_FP_ROUND_TO_INF
#define org_jocl_CL_CL_FP_ROUND_TO_INF 16i64
#undef org_jocl_CL_CL_FP_FMA
#define org_jocl_CL_CL_FP_FMA 32i64
#undef org_jocl_CL_CL_FP_SOFT_FLOAT
#define org_jocl_CL_CL_FP_SOFT_FLOAT 64i64
#undef org_jocl_CL_CL_NONE
#define org_jocl_CL_CL_NONE 0L
#undef org_jocl_CL_CL_READ_ONLY_CACHE
#define org_jocl_CL_CL_READ_ONLY_CACHE 1L
#undef org_jocl_CL_CL_READ_WRITE_CACHE
#define org_jocl_CL_CL_READ_WRITE_CACHE 2L
#undef org_jocl_CL_CL_LOCAL
#define org_jocl_CL_CL_LOCAL 1L
#undef org_jocl_CL_CL_GLOBAL
#define org_jocl_CL_CL_GLOBAL 2L
#undef org_jocl_CL_CL_EXEC_KERNEL
#define org_jocl_CL_CL_EXEC_KERNEL 1i64
#undef org_jocl_CL_CL_EXEC_NATIVE_KERNEL
#define org_jocl_CL_CL_EXEC_NATIVE_KERNEL 2i64
#undef org_jocl_CL_CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE
#define org_jocl_CL_CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE 1i64
#undef org_jocl_CL_CL_QUEUE_PROFILING_ENABLE
#define org_jocl_CL_CL_QUEUE_PROFILING_ENABLE 2i64
#undef org_jocl_CL_CL_CONTEXT_REFERENCE_COUNT
#define org_jocl_CL_CL_CONTEXT_REFERENCE_COUNT 4224L
#undef org_jocl_CL_CL_CONTEXT_DEVICES
#define org_jocl_CL_CL_CONTEXT_DEVICES 4225L
#undef org_jocl_CL_CL_CONTEXT_PROPERTIES
#define org_jocl_CL_CL_CONTEXT_PROPERTIES 4226L
#undef org_jocl_CL_CL_CONTEXT_NUM_DEVICES
#define org_jocl_CL_CL_CONTEXT_NUM_DEVICES 4227L
#undef org_jocl_CL_CL_CONTEXT_PLATFORM
#define org_jocl_CL_CL_CONTEXT_PLATFORM 4228L
#undef org_jocl_CL_CL_QUEUE_CONTEXT
#define org_jocl_CL_CL_QUEUE_CONTEXT 4240L
#undef org_jocl_CL_CL_QUEUE_DEVICE
#define org_jocl_CL_CL_QUEUE_DEVICE 4241L
#undef org_jocl_CL_CL_QUEUE_REFERENCE_COUNT
#define org_jocl_CL_CL_QUEUE_REFERENCE_COUNT 4242L
#undef org_jocl_CL_CL_QUEUE_PROPERTIES
#define org_jocl_CL_CL_QUEUE_PROPERTIES 4243L
#undef org_jocl_CL_CL_MEM_READ_WRITE
#define org_jocl_CL_CL_MEM_READ_WRITE 1i64
#undef org_jocl_CL_CL_MEM_WRITE_ONLY
#define org_jocl_CL_CL_MEM_WRITE_ONLY 2i64
#undef org_jocl_CL_CL_MEM_READ_ONLY
#define org_jocl_CL_CL_MEM_READ_ONLY 4i64
#undef org_jocl_CL_CL_MEM_USE_HOST_PTR
#define org_jocl_CL_CL_MEM_USE_HOST_PTR 8i64
#undef org_jocl_CL_CL_MEM_ALLOC_HOST_PTR
#define org_jocl_CL_CL_MEM_ALLOC_HOST_PTR 16i64
#undef org_jocl_CL_CL_MEM_COPY_HOST_PTR
#define org_jocl_CL_CL_MEM_COPY_HOST_PTR 32i64
#undef org_jocl_CL_CL_R
#define org_jocl_CL_CL_R 4272L
#undef org_jocl_CL_CL_A
#define org_jocl_CL_CL_A 4273L
#undef org_jocl_CL_CL_RG
#define org_jocl_CL_CL_RG 4274L
#undef org_jocl_CL_CL_RA
#define org_jocl_CL_CL_RA 4275L
#undef org_jocl_CL_CL_RGB
#define org_jocl_CL_CL_RGB 4276L
#undef org_jocl_CL_CL_RGBA
#define org_jocl_CL_CL_RGBA 4277L
#undef org_jocl_CL_CL_BGRA
#define org_jocl_CL_CL_BGRA 4278L
#undef org_jocl_CL_CL_ARGB
#define org_jocl_CL_CL_ARGB 4279L
#undef org_jocl_CL_CL_INTENSITY
#define org_jocl_CL_CL_INTENSITY 4280L
#undef org_jocl_CL_CL_LUMINANCE
#define org_jocl_CL_CL_LUMINANCE 4281L
#undef org_jocl_CL_CL_Rx
#define org_jocl_CL_CL_Rx 4282L
#undef org_jocl_CL_CL_RGx
#define org_jocl_CL_CL_RGx 4283L
#undef org_jocl_CL_CL_RGBx
#define org_jocl_CL_CL_RGBx 4284L
#undef org_jocl_CL_CL_SNORM_INT8
#define org_jocl_CL_CL_SNORM_INT8 4304L
#undef org_jocl_CL_CL_SNORM_INT16
#define org_jocl_CL_CL_SNORM_INT16 4305L
#undef org_jocl_CL_CL_UNORM_INT8
#define org_jocl_CL_CL_UNORM_INT8 4306L
#undef org_jocl_CL_CL_UNORM_INT16
#define org_jocl_CL_CL_UNORM_INT16 4307L
#undef org_jocl_CL_CL_UNORM_SHORT_565
#define org_jocl_CL_CL_UNORM_SHORT_565 4308L
#undef org_jocl_CL_CL_UNORM_SHORT_555
#define org_jocl_CL_CL_UNORM_SHORT_555 4309L
#undef org_jocl_CL_CL_UNORM_INT_101010
#define org_jocl_CL_CL_UNORM_INT_101010 4310L
#undef org_jocl_CL_CL_SIGNED_INT8
#define org_jocl_CL_CL_SIGNED_INT8 4311L
#undef org_jocl_CL_CL_SIGNED_INT16
#define org_jocl_CL_CL_SIGNED_INT16 4312L
#undef org_jocl_CL_CL_SIGNED_INT32
#define org_jocl_CL_CL_SIGNED_INT32 4313L
#undef org_jocl_CL_CL_UNSIGNED_INT8
#define org_jocl_CL_CL_UNSIGNED_INT8 4314L
#undef org_jocl_CL_CL_UNSIGNED_INT16
#define org_jocl_CL_CL_UNSIGNED_INT16 4315L
#undef org_jocl_CL_CL_UNSIGNED_INT32
#define org_jocl_CL_CL_UNSIGNED_INT32 4316L
#undef org_jocl_CL_CL_HALF_FLOAT
#define org_jocl_CL_CL_HALF_FLOAT 4317L
#undef org_jocl_CL_CL_FLOAT
#define org_jocl_CL_CL_FLOAT 4318L
#undef org_jocl_CL_CL_MEM_OBJECT_BUFFER
#define org_jocl_CL_CL_MEM_OBJECT_BUFFER 4336L
#undef org_jocl_CL_CL_MEM_OBJECT_IMAGE2D
#define org_jocl_CL_CL_MEM_OBJECT_IMAGE2D 4337L
#undef org_jocl_CL_CL_MEM_OBJECT_IMAGE3D
#define org_jocl_CL_CL_MEM_OBJECT_IMAGE3D 4338L
#undef org_jocl_CL_CL_MEM_TYPE
#define org_jocl_CL_CL_MEM_TYPE 4352L
#undef org_jocl_CL_CL_MEM_FLAGS
#define org_jocl_CL_CL_MEM_FLAGS 4353L
#undef org_jocl_CL_CL_MEM_SIZE
#define org_jocl_CL_CL_MEM_SIZE 4354L
#undef org_jocl_CL_CL_MEM_HOST_PTR
#define org_jocl_CL_CL_MEM_HOST_PTR 4355L
#undef org_jocl_CL_CL_MEM_MAP_COUNT
#define org_jocl_CL_CL_MEM_MAP_COUNT 4356L
#undef org_jocl_CL_CL_MEM_REFERENCE_COUNT
#define org_jocl_CL_CL_MEM_REFERENCE_COUNT 4357L
#undef org_jocl_CL_CL_MEM_CONTEXT
#define org_jocl_CL_CL_MEM_CONTEXT 4358L
#undef org_jocl_CL_CL_MEM_ASSOCIATED_MEMOBJECT
#define org_jocl_CL_CL_MEM_ASSOCIATED_MEMOBJECT 4359L
#undef org_jocl_CL_CL_MEM_OFFSET
#define org_jocl_CL_CL_MEM_OFFSET 4360L
#undef org_jocl_CL_CL_IMAGE_FORMAT
#define org_jocl_CL_CL_IMAGE_FORMAT 4368L
#undef org_jocl_CL_CL_IMAGE_ELEMENT_SIZE
#define org_jocl_CL_CL_IMAGE_ELEMENT_SIZE 4369L
#undef org_jocl_CL_CL_IMAGE_ROW_PITCH
#define org_jocl_CL_CL_IMAGE_ROW_PITCH 4370L
#undef org_jocl_CL_CL_IMAGE_SLICE_PITCH
#define org_jocl_CL_CL_IMAGE_SLICE_PITCH 4371L
#undef org_jocl_CL_CL_IMAGE_WIDTH
#define org_jocl_CL_CL_IMAGE_WIDTH 4372L
#undef org_jocl_CL_CL_IMAGE_HEIGHT
#define org_jocl_CL_CL_IMAGE_HEIGHT 4373L
#undef org_jocl_CL_CL_IMAGE_DEPTH
#define org_jocl_CL_CL_IMAGE_DEPTH 4374L
#undef org_jocl_CL_CL_ADDRESS_NONE
#define org_jocl_CL_CL_ADDRESS_NONE 4400L
#undef org_jocl_CL_CL_ADDRESS_CLAMP_TO_EDGE
#define org_jocl_CL_CL_ADDRESS_CLAMP_TO_EDGE 4401L
#undef org_jocl_CL_CL_ADDRESS_CLAMP
#define org_jocl_CL_CL_ADDRESS_CLAMP 4402L
#undef org_jocl_CL_CL_ADDRESS_REPEAT
#define org_jocl_CL_CL_ADDRESS_REPEAT 4403L
#undef org_jocl_CL_CL_ADDRESS_MIRRORED_REPEAT
#define org_jocl_CL_CL_ADDRESS_MIRRORED_REPEAT 4404L
#undef org_jocl_CL_CL_FILTER_NEAREST
#define org_jocl_CL_CL_FILTER_NEAREST 4416L
#undef org_jocl_CL_CL_FILTER_LINEAR
#define org_jocl_CL_CL_FILTER_LINEAR 4417L
#undef org_jocl_CL_CL_SAMPLER_REFERENCE_COUNT
#define org_jocl_CL_CL_SAMPLER_REFERENCE_COUNT 4432L
#undef org_jocl_CL_CL_SAMPLER_CONTEXT
#define org_jocl_CL_CL_SAMPLER_CONTEXT 4433L
#undef org_jocl_CL_CL_SAMPLER_NORMALIZED_COORDS
#define org_jocl_CL_CL_SAMPLER_NORMALIZED_COORDS 4434L
#undef org_jocl_CL_CL_SAMPLER_ADDRESSING_MODE
#define org_jocl_CL_CL_SAMPLER_ADDRESSING_MODE 4435L
#undef org_jocl_CL_CL_SAMPLER_FILTER_MODE
#define org_jocl_CL_CL_SAMPLER_FILTER_MODE 4436L
#undef org_jocl_CL_CL_MAP_READ
#define org_jocl_CL_CL_MAP_READ 1i64
#undef org_jocl_CL_CL_MAP_WRITE
#define org_jocl_CL_CL_MAP_WRITE 2i64
#undef org_jocl_CL_CL_PROGRAM_REFERENCE_COUNT
#define org_jocl_CL_CL_PROGRAM_REFERENCE_COUNT 4448L
#undef org_jocl_CL_CL_PROGRAM_CONTEXT
#define org_jocl_CL_CL_PROGRAM_CONTEXT 4449L
#undef org_jocl_CL_CL_PROGRAM_NUM_DEVICES
#define org_jocl_CL_CL_PROGRAM_NUM_DEVICES 4450L
#undef org_jocl_CL_CL_PROGRAM_DEVICES
#define org_jocl_CL_CL_PROGRAM_DEVICES 4451L
#undef org_jocl_CL_CL_PROGRAM_SOURCE
#define org_jocl_CL_CL_PROGRAM_SOURCE 4452L
#undef org_jocl_CL_CL_PROGRAM_BINARY_SIZES
#define org_jocl_CL_CL_PROGRAM_BINARY_SIZES 4453L
#undef org_jocl_CL_CL_PROGRAM_BINARIES
#define org_jocl_CL_CL_PROGRAM_BINARIES 4454L
#undef org_jocl_CL_CL_PROGRAM_BUILD_STATUS
#define org_jocl_CL_CL_PROGRAM_BUILD_STATUS 4481L
#undef org_jocl_CL_CL_PROGRAM_BUILD_OPTIONS
#define org_jocl_CL_CL_PROGRAM_BUILD_OPTIONS 4482L
#undef org_jocl_CL_CL_PROGRAM_BUILD_LOG
#define org_jocl_CL_CL_PROGRAM_BUILD_LOG 4483L
#undef org_jocl_CL_CL_BUILD_SUCCESS
#define org_jocl_CL_CL_BUILD_SUCCESS 0L
#undef org_jocl_CL_CL_BUILD_NONE
#define org_jocl_CL_CL_BUILD_NONE -1L
#undef org_jocl_CL_CL_BUILD_ERROR
#define org_jocl_CL_CL_BUILD_ERROR -2L
#undef org_jocl_CL_CL_BUILD_IN_PROGRESS
#define org_jocl_CL_CL_BUILD_IN_PROGRESS -3L
#undef org_jocl_CL_CL_KERNEL_FUNCTION_NAME
#define org_jocl_CL_CL_KERNEL_FUNCTION_NAME 4496L
#undef org_jocl_CL_CL_KERNEL_NUM_ARGS
#define org_jocl_CL_CL_KERNEL_NUM_ARGS 4497L
#undef org_jocl_CL_CL_KERNEL_REFERENCE_COUNT
#define org_jocl_CL_CL_KERNEL_REFERENCE_COUNT 4498L
#undef org_jocl_CL_CL_KERNEL_CONTEXT
#define org_jocl_CL_CL_KERNEL_CONTEXT 4499L
#undef org_jocl_CL_CL_KERNEL_PROGRAM
#define org_jocl_CL_CL_KERNEL_PROGRAM 4500L
#undef org_jocl_CL_CL_KERNEL_WORK_GROUP_SIZE
#define org_jocl_CL_CL_KERNEL_WORK_GROUP_SIZE 4528L
#undef org_jocl_CL_CL_KERNEL_COMPILE_WORK_GROUP_SIZE
#define org_jocl_CL_CL_KERNEL_COMPILE_WORK_GROUP_SIZE 4529L
#undef org_jocl_CL_CL_KERNEL_LOCAL_MEM_SIZE
#define org_jocl_CL_CL_KERNEL_LOCAL_MEM_SIZE 4530L
#undef org_jocl_CL_CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE
#define org_jocl_CL_CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE 4531L
#undef org_jocl_CL_CL_KERNEL_PRIVATE_MEM_SIZE
#define org_jocl_CL_CL_KERNEL_PRIVATE_MEM_SIZE 4532L
#undef org_jocl_CL_CL_EVENT_COMMAND_QUEUE
#define org_jocl_CL_CL_EVENT_COMMAND_QUEUE 4560L
#undef org_jocl_CL_CL_EVENT_COMMAND_TYPE
#define org_jocl_CL_CL_EVENT_COMMAND_TYPE 4561L
#undef org_jocl_CL_CL_EVENT_REFERENCE_COUNT
#define org_jocl_CL_CL_EVENT_REFERENCE_COUNT 4562L
#undef org_jocl_CL_CL_EVENT_COMMAND_EXECUTION_STATUS
#define org_jocl_CL_CL_EVENT_COMMAND_EXECUTION_STATUS 4563L
#undef org_jocl_CL_CL_EVENT_CONTEXT
#define org_jocl_CL_CL_EVENT_CONTEXT 4564L
#undef org_jocl_CL_CL_COMMAND_NDRANGE_KERNEL
#define org_jocl_CL_CL_COMMAND_NDRANGE_KERNEL 4592L
#undef org_jocl_CL_CL_COMMAND_TASK
#define org_jocl_CL_CL_COMMAND_TASK 4593L
#undef org_jocl_CL_CL_COMMAND_NATIVE_KERNEL
#define org_jocl_CL_CL_COMMAND_NATIVE_KERNEL 4594L
#undef org_jocl_CL_CL_COMMAND_READ_BUFFER
#define org_jocl_CL_CL_COMMAND_READ_BUFFER 4595L
#undef org_jocl_CL_CL_COMMAND_WRITE_BUFFER
#define org_jocl_CL_CL_COMMAND_WRITE_BUFFER 4596L
#undef org_jocl_CL_CL_COMMAND_COPY_BUFFER
#define org_jocl_CL_CL_COMMAND_COPY_BUFFER 4597L
#undef org_jocl_CL_CL_COMMAND_READ_IMAGE
#define org_jocl_CL_CL_COMMAND_READ_IMAGE 4598L
#undef org_jocl_CL_CL_COMMAND_WRITE_IMAGE
#define org_jocl_CL_CL_COMMAND_WRITE_IMAGE 4599L
#undef org_jocl_CL_CL_COMMAND_COPY_IMAGE
#define org_jocl_CL_CL_COMMAND_COPY_IMAGE 4600L
#undef org_jocl_CL_CL_COMMAND_COPY_IMAGE_TO_BUFFER
#define org_jocl_CL_CL_COMMAND_COPY_IMAGE_TO_BUFFER 4601L
#undef org_jocl_CL_CL_COMMAND_COPY_BUFFER_TO_IMAGE
#define org_jocl_CL_CL_COMMAND_COPY_BUFFER_TO_IMAGE 4602L
#undef org_jocl_CL_CL_COMMAND_MAP_BUFFER
#define org_jocl_CL_CL_COMMAND_MAP_BUFFER 4603L
#undef org_jocl_CL_CL_COMMAND_MAP_IMAGE
#define org_jocl_CL_CL_COMMAND_MAP_IMAGE 4604L
#undef org_jocl_CL_CL_COMMAND_UNMAP_MEM_OBJECT
#define org_jocl_CL_CL_COMMAND_UNMAP_MEM_OBJECT 4605L
#undef org_jocl_CL_CL_COMMAND_MARKER
#define org_jocl_CL_CL_COMMAND_MARKER 4606L
#undef org_jocl_CL_CL_COMMAND_ACQUIRE_GL_OBJECTS
#define org_jocl_CL_CL_COMMAND_ACQUIRE_GL_OBJECTS 4607L
#undef org_jocl_CL_CL_COMMAND_RELEASE_GL_OBJECTS
#define org_jocl_CL_CL_COMMAND_RELEASE_GL_OBJECTS 4608L
#undef org_jocl_CL_CL_COMMAND_READ_BUFFER_RECT
#define org_jocl_CL_CL_COMMAND_READ_BUFFER_RECT 4609L
#undef org_jocl_CL_CL_COMMAND_WRITE_BUFFER_RECT
#define org_jocl_CL_CL_COMMAND_WRITE_BUFFER_RECT 4610L
#undef org_jocl_CL_CL_COMMAND_COPY_BUFFER_RECT
#define org_jocl_CL_CL_COMMAND_COPY_BUFFER_RECT 4611L
#undef org_jocl_CL_CL_COMMAND_USER
#define org_jocl_CL_CL_COMMAND_USER 4612L
#undef org_jocl_CL_CL_COMPLETE
#define org_jocl_CL_CL_COMPLETE 0L
#undef org_jocl_CL_CL_RUNNING
#define org_jocl_CL_CL_RUNNING 1L
#undef org_jocl_CL_CL_SUBMITTED
#define org_jocl_CL_CL_SUBMITTED 2L
#undef org_jocl_CL_CL_QUEUED
#define org_jocl_CL_CL_QUEUED 3L
#undef org_jocl_CL_CL_BUFFER_CREATE_TYPE_REGION
#define org_jocl_CL_CL_BUFFER_CREATE_TYPE_REGION 4640L
#undef org_jocl_CL_CL_PROFILING_COMMAND_QUEUED
#define org_jocl_CL_CL_PROFILING_COMMAND_QUEUED 4736L
#undef org_jocl_CL_CL_PROFILING_COMMAND_SUBMIT
#define org_jocl_CL_CL_PROFILING_COMMAND_SUBMIT 4737L
#undef org_jocl_CL_CL_PROFILING_COMMAND_START
#define org_jocl_CL_CL_PROFILING_COMMAND_START 4738L
#undef org_jocl_CL_CL_PROFILING_COMMAND_END
#define org_jocl_CL_CL_PROFILING_COMMAND_END 4739L
#undef org_jocl_CL_CL_GL_OBJECT_BUFFER
#define org_jocl_CL_CL_GL_OBJECT_BUFFER 8192L
#undef org_jocl_CL_CL_GL_OBJECT_TEXTURE2D
#define org_jocl_CL_CL_GL_OBJECT_TEXTURE2D 8193L
#undef org_jocl_CL_CL_GL_OBJECT_TEXTURE3D
#define org_jocl_CL_CL_GL_OBJECT_TEXTURE3D 8194L
#undef org_jocl_CL_CL_GL_OBJECT_RENDERBUFFER
#define org_jocl_CL_CL_GL_OBJECT_RENDERBUFFER 8195L
#undef org_jocl_CL_CL_GL_TEXTURE_TARGET
#define org_jocl_CL_CL_GL_TEXTURE_TARGET 8196L
#undef org_jocl_CL_CL_GL_MIPMAP_LEVEL
#define org_jocl_CL_CL_GL_MIPMAP_LEVEL 8197L
#undef org_jocl_CL_CL_CURRENT_DEVICE_FOR_GL_CONTEXT_KHR
#define org_jocl_CL_CL_CURRENT_DEVICE_FOR_GL_CONTEXT_KHR 8198L
#undef org_jocl_CL_CL_DEVICES_FOR_GL_CONTEXT_KHR
#define org_jocl_CL_CL_DEVICES_FOR_GL_CONTEXT_KHR 8199L
#undef org_jocl_CL_CL_GL_CONTEXT_KHR
#define org_jocl_CL_CL_GL_CONTEXT_KHR 8200L
#undef org_jocl_CL_CL_EGL_DISPLAY_KHR
#define org_jocl_CL_CL_EGL_DISPLAY_KHR 8201L
#undef org_jocl_CL_CL_GLX_DISPLAY_KHR
#define org_jocl_CL_CL_GLX_DISPLAY_KHR 8202L
#undef org_jocl_CL_CL_WGL_HDC_KHR
#define org_jocl_CL_CL_WGL_HDC_KHR 8203L
#undef org_jocl_CL_CL_CGL_SHAREGROUP_KHR
#define org_jocl_CL_CL_CGL_SHAREGROUP_KHR 8204L
/*
 * Class:     org_jocl_CL
 * Method:    setLogLevelNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jocl_CL_setLogLevelNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jocl_CL
 * Method:    allocateAlignedNative
 * Signature: (IILorg/jocl/Pointer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_jocl_CL_allocateAlignedNative
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    freeAlignedNative
 * Signature: (Lorg/jocl/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_jocl_CL_freeAlignedNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clGetPlatformIDsNative
 * Signature: (I[Lorg/jocl/cl_platform_id;[I)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clGetPlatformIDsNative
  (JNIEnv *, jclass, jint, jobjectArray, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clGetPlatformInfoNative
 * Signature: (Lorg/jocl/cl_platform_id;IJLorg/jocl/Pointer;[J)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clGetPlatformInfoNative
  (JNIEnv *, jclass, jobject, jint, jlong, jobject, jlongArray);

/*
 * Class:     org_jocl_CL
 * Method:    clGetDeviceIDsNative
 * Signature: (Lorg/jocl/cl_platform_id;JI[Lorg/jocl/cl_device_id;[I)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clGetDeviceIDsNative
  (JNIEnv *, jclass, jobject, jlong, jint, jobjectArray, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clGetDeviceInfoNative
 * Signature: (Lorg/jocl/cl_device_id;IJLorg/jocl/Pointer;[J)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clGetDeviceInfoNative
  (JNIEnv *, jclass, jobject, jint, jlong, jobject, jlongArray);

/*
 * Class:     org_jocl_CL
 * Method:    clCreateContextNative
 * Signature: (Lorg/jocl/cl_context_properties;I[Lorg/jocl/cl_device_id;Lorg/jocl/CreateContextFunction;Ljava/lang/Object;[I)Lorg/jocl/cl_context;
 */
JNIEXPORT jobject JNICALL Java_org_jocl_CL_clCreateContextNative
  (JNIEnv *, jclass, jobject, jint, jobjectArray, jobject, jobject, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clCreateContextFromTypeNative
 * Signature: (Lorg/jocl/cl_context_properties;JLorg/jocl/CreateContextFunction;Ljava/lang/Object;[I)Lorg/jocl/cl_context;
 */
JNIEXPORT jobject JNICALL Java_org_jocl_CL_clCreateContextFromTypeNative
  (JNIEnv *, jclass, jobject, jlong, jobject, jobject, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clRetainContextNative
 * Signature: (Lorg/jocl/cl_context;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clRetainContextNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clReleaseContextNative
 * Signature: (Lorg/jocl/cl_context;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clReleaseContextNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clGetContextInfoNative
 * Signature: (Lorg/jocl/cl_context;IJLorg/jocl/Pointer;[J)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clGetContextInfoNative
  (JNIEnv *, jclass, jobject, jint, jlong, jobject, jlongArray);

/*
 * Class:     org_jocl_CL
 * Method:    clCreateCommandQueueNative
 * Signature: (Lorg/jocl/cl_context;Lorg/jocl/cl_device_id;J[I)Lorg/jocl/cl_command_queue;
 */
JNIEXPORT jobject JNICALL Java_org_jocl_CL_clCreateCommandQueueNative
  (JNIEnv *, jclass, jobject, jobject, jlong, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clRetainCommandQueueNative
 * Signature: (Lorg/jocl/cl_command_queue;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clRetainCommandQueueNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clReleaseCommandQueueNative
 * Signature: (Lorg/jocl/cl_command_queue;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clReleaseCommandQueueNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clGetCommandQueueInfoNative
 * Signature: (Lorg/jocl/cl_command_queue;IJLorg/jocl/Pointer;[J)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clGetCommandQueueInfoNative
  (JNIEnv *, jclass, jobject, jint, jlong, jobject, jlongArray);

/*
 * Class:     org_jocl_CL
 * Method:    clSetCommandQueuePropertyNative
 * Signature: (Lorg/jocl/cl_command_queue;JZ[J)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clSetCommandQueuePropertyNative
  (JNIEnv *, jclass, jobject, jlong, jboolean, jlongArray);

/*
 * Class:     org_jocl_CL
 * Method:    clCreateBufferNative
 * Signature: (Lorg/jocl/cl_context;JJLorg/jocl/Pointer;[I)Lorg/jocl/cl_mem;
 */
JNIEXPORT jobject JNICALL Java_org_jocl_CL_clCreateBufferNative
  (JNIEnv *, jclass, jobject, jlong, jlong, jobject, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clCreateSubBufferNative
 * Signature: (Lorg/jocl/cl_mem;IILorg/jocl/Pointer;[I)Lorg/jocl/cl_mem;
 */
JNIEXPORT jobject JNICALL Java_org_jocl_CL_clCreateSubBufferNative
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clCreateImage2DNative
 * Signature: (Lorg/jocl/cl_context;J[Lorg/jocl/cl_image_format;JJJLorg/jocl/Pointer;[I)Lorg/jocl/cl_mem;
 */
JNIEXPORT jobject JNICALL Java_org_jocl_CL_clCreateImage2DNative
  (JNIEnv *, jclass, jobject, jlong, jobjectArray, jlong, jlong, jlong, jobject, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clCreateImage3DNative
 * Signature: (Lorg/jocl/cl_context;J[Lorg/jocl/cl_image_format;JJJJJLorg/jocl/Pointer;[I)Lorg/jocl/cl_mem;
 */
JNIEXPORT jobject JNICALL Java_org_jocl_CL_clCreateImage3DNative
  (JNIEnv *, jclass, jobject, jlong, jobjectArray, jlong, jlong, jlong, jlong, jlong, jobject, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clRetainMemObjectNative
 * Signature: (Lorg/jocl/cl_mem;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clRetainMemObjectNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clReleaseMemObjectNative
 * Signature: (Lorg/jocl/cl_mem;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clReleaseMemObjectNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clGetSupportedImageFormatsNative
 * Signature: (Lorg/jocl/cl_context;JII[Lorg/jocl/cl_image_format;[I)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clGetSupportedImageFormatsNative
  (JNIEnv *, jclass, jobject, jlong, jint, jint, jobjectArray, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clGetMemObjectInfoNative
 * Signature: (Lorg/jocl/cl_mem;IJLorg/jocl/Pointer;[J)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clGetMemObjectInfoNative
  (JNIEnv *, jclass, jobject, jint, jlong, jobject, jlongArray);

/*
 * Class:     org_jocl_CL
 * Method:    clGetImageInfoNative
 * Signature: (Lorg/jocl/cl_mem;IJLorg/jocl/Pointer;[J)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clGetImageInfoNative
  (JNIEnv *, jclass, jobject, jint, jlong, jobject, jlongArray);

/*
 * Class:     org_jocl_CL
 * Method:    clSetMemObjectDestructorCallbackNative
 * Signature: (Lorg/jocl/cl_mem;Lorg/jocl/MemObjectDestructorCallbackFunction;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clSetMemObjectDestructorCallbackNative
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clCreateSamplerNative
 * Signature: (Lorg/jocl/cl_context;ZII[I)Lorg/jocl/cl_sampler;
 */
JNIEXPORT jobject JNICALL Java_org_jocl_CL_clCreateSamplerNative
  (JNIEnv *, jclass, jobject, jboolean, jint, jint, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clRetainSamplerNative
 * Signature: (Lorg/jocl/cl_sampler;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clRetainSamplerNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clReleaseSamplerNative
 * Signature: (Lorg/jocl/cl_sampler;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clReleaseSamplerNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clGetSamplerInfoNative
 * Signature: (Lorg/jocl/cl_sampler;IJLorg/jocl/Pointer;[J)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clGetSamplerInfoNative
  (JNIEnv *, jclass, jobject, jint, jlong, jobject, jlongArray);

/*
 * Class:     org_jocl_CL
 * Method:    clCreateProgramWithSourceNative
 * Signature: (Lorg/jocl/cl_context;I[Ljava/lang/String;[J[I)Lorg/jocl/cl_program;
 */
JNIEXPORT jobject JNICALL Java_org_jocl_CL_clCreateProgramWithSourceNative
  (JNIEnv *, jclass, jobject, jint, jobjectArray, jlongArray, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clCreateProgramWithBinaryNative
 * Signature: (Lorg/jocl/cl_context;I[Lorg/jocl/cl_device_id;[J[[B[I[I)Lorg/jocl/cl_program;
 */
JNIEXPORT jobject JNICALL Java_org_jocl_CL_clCreateProgramWithBinaryNative
  (JNIEnv *, jclass, jobject, jint, jobjectArray, jlongArray, jobjectArray, jintArray, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clRetainProgramNative
 * Signature: (Lorg/jocl/cl_program;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clRetainProgramNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clReleaseProgramNative
 * Signature: (Lorg/jocl/cl_program;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clReleaseProgramNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clBuildProgramNative
 * Signature: (Lorg/jocl/cl_program;I[Lorg/jocl/cl_device_id;Ljava/lang/String;Lorg/jocl/BuildProgramFunction;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clBuildProgramNative
  (JNIEnv *, jclass, jobject, jint, jobjectArray, jstring, jobject, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clUnloadCompilerNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clUnloadCompilerNative
  (JNIEnv *, jclass);

/*
 * Class:     org_jocl_CL
 * Method:    clGetProgramInfoNative
 * Signature: (Lorg/jocl/cl_program;IJLorg/jocl/Pointer;[J)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clGetProgramInfoNative
  (JNIEnv *, jclass, jobject, jint, jlong, jobject, jlongArray);

/*
 * Class:     org_jocl_CL
 * Method:    clGetProgramBuildInfoNative
 * Signature: (Lorg/jocl/cl_program;Lorg/jocl/cl_device_id;IJLorg/jocl/Pointer;[J)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clGetProgramBuildInfoNative
  (JNIEnv *, jclass, jobject, jobject, jint, jlong, jobject, jlongArray);

/*
 * Class:     org_jocl_CL
 * Method:    clCreateKernelNative
 * Signature: (Lorg/jocl/cl_program;Ljava/lang/String;[I)Lorg/jocl/cl_kernel;
 */
JNIEXPORT jobject JNICALL Java_org_jocl_CL_clCreateKernelNative
  (JNIEnv *, jclass, jobject, jstring, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clCreateKernelsInProgramNative
 * Signature: (Lorg/jocl/cl_program;I[Lorg/jocl/cl_kernel;[I)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clCreateKernelsInProgramNative
  (JNIEnv *, jclass, jobject, jint, jobjectArray, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clRetainKernelNative
 * Signature: (Lorg/jocl/cl_kernel;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clRetainKernelNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clReleaseKernelNative
 * Signature: (Lorg/jocl/cl_kernel;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clReleaseKernelNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clSetKernelArgNative
 * Signature: (Lorg/jocl/cl_kernel;IJLorg/jocl/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clSetKernelArgNative
  (JNIEnv *, jclass, jobject, jint, jlong, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clGetKernelInfoNative
 * Signature: (Lorg/jocl/cl_kernel;IJLorg/jocl/Pointer;[J)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clGetKernelInfoNative
  (JNIEnv *, jclass, jobject, jint, jlong, jobject, jlongArray);

/*
 * Class:     org_jocl_CL
 * Method:    clGetKernelWorkGroupInfoNative
 * Signature: (Lorg/jocl/cl_kernel;Lorg/jocl/cl_device_id;IJLorg/jocl/Pointer;[J)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clGetKernelWorkGroupInfoNative
  (JNIEnv *, jclass, jobject, jobject, jint, jlong, jobject, jlongArray);

/*
 * Class:     org_jocl_CL
 * Method:    clWaitForEventsNative
 * Signature: (I[Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clWaitForEventsNative
  (JNIEnv *, jclass, jint, jobjectArray);

/*
 * Class:     org_jocl_CL
 * Method:    clGetEventInfoNative
 * Signature: (Lorg/jocl/cl_event;IJLorg/jocl/Pointer;[J)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clGetEventInfoNative
  (JNIEnv *, jclass, jobject, jint, jlong, jobject, jlongArray);

/*
 * Class:     org_jocl_CL
 * Method:    clCreateUserEventNative
 * Signature: (Lorg/jocl/cl_context;[I)Lorg/jocl/cl_event;
 */
JNIEXPORT jobject JNICALL Java_org_jocl_CL_clCreateUserEventNative
  (JNIEnv *, jclass, jobject, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clRetainEventNative
 * Signature: (Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clRetainEventNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clReleaseEventNative
 * Signature: (Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clReleaseEventNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clSetUserEventStatusNative
 * Signature: (Lorg/jocl/cl_event;I)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clSetUserEventStatusNative
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_jocl_CL
 * Method:    clSetEventCallbackNative
 * Signature: (Lorg/jocl/cl_event;ILorg/jocl/EventCallbackFunction;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clSetEventCallbackNative
  (JNIEnv *, jclass, jobject, jint, jobject, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clGetEventProfilingInfoNative
 * Signature: (Lorg/jocl/cl_event;IJLorg/jocl/Pointer;[J)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clGetEventProfilingInfoNative
  (JNIEnv *, jclass, jobject, jint, jlong, jobject, jlongArray);

/*
 * Class:     org_jocl_CL
 * Method:    clFlushNative
 * Signature: (Lorg/jocl/cl_command_queue;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clFlushNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clFinishNative
 * Signature: (Lorg/jocl/cl_command_queue;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clFinishNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueReadBufferNative
 * Signature: (Lorg/jocl/cl_command_queue;Lorg/jocl/cl_mem;ZJJLorg/jocl/Pointer;I[Lorg/jocl/cl_event;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clEnqueueReadBufferNative
  (JNIEnv *, jclass, jobject, jobject, jboolean, jlong, jlong, jobject, jint, jobjectArray, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueReadBufferRectNative
 * Signature: (Lorg/jocl/cl_command_queue;Lorg/jocl/cl_mem;Z[J[J[JJJJJLorg/jocl/Pointer;I[Lorg/jocl/cl_event;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clEnqueueReadBufferRectNative
  (JNIEnv *, jclass, jobject, jobject, jboolean, jlongArray, jlongArray, jlongArray, jlong, jlong, jlong, jlong, jobject, jint, jobjectArray, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueWriteBufferNative
 * Signature: (Lorg/jocl/cl_command_queue;Lorg/jocl/cl_mem;ZJJLorg/jocl/Pointer;I[Lorg/jocl/cl_event;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clEnqueueWriteBufferNative
  (JNIEnv *, jclass, jobject, jobject, jboolean, jlong, jlong, jobject, jint, jobjectArray, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueWriteBufferRectNative
 * Signature: (Lorg/jocl/cl_command_queue;Lorg/jocl/cl_mem;Z[J[J[JJJJJLorg/jocl/Pointer;I[Lorg/jocl/cl_event;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clEnqueueWriteBufferRectNative
  (JNIEnv *, jclass, jobject, jobject, jboolean, jlongArray, jlongArray, jlongArray, jlong, jlong, jlong, jlong, jobject, jint, jobjectArray, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueCopyBufferNative
 * Signature: (Lorg/jocl/cl_command_queue;Lorg/jocl/cl_mem;Lorg/jocl/cl_mem;JJJI[Lorg/jocl/cl_event;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clEnqueueCopyBufferNative
  (JNIEnv *, jclass, jobject, jobject, jobject, jlong, jlong, jlong, jint, jobjectArray, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueCopyBufferRectNative
 * Signature: (Lorg/jocl/cl_command_queue;Lorg/jocl/cl_mem;Lorg/jocl/cl_mem;[J[J[JJJJJI[Lorg/jocl/cl_event;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clEnqueueCopyBufferRectNative
  (JNIEnv *, jclass, jobject, jobject, jobject, jlongArray, jlongArray, jlongArray, jlong, jlong, jlong, jlong, jint, jobjectArray, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueReadImageNative
 * Signature: (Lorg/jocl/cl_command_queue;Lorg/jocl/cl_mem;Z[J[JJJLorg/jocl/Pointer;I[Lorg/jocl/cl_event;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clEnqueueReadImageNative
  (JNIEnv *, jclass, jobject, jobject, jboolean, jlongArray, jlongArray, jlong, jlong, jobject, jint, jobjectArray, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueWriteImageNative
 * Signature: (Lorg/jocl/cl_command_queue;Lorg/jocl/cl_mem;Z[J[JJJLorg/jocl/Pointer;I[Lorg/jocl/cl_event;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clEnqueueWriteImageNative
  (JNIEnv *, jclass, jobject, jobject, jboolean, jlongArray, jlongArray, jlong, jlong, jobject, jint, jobjectArray, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueCopyImageNative
 * Signature: (Lorg/jocl/cl_command_queue;Lorg/jocl/cl_mem;Lorg/jocl/cl_mem;[J[J[JI[Lorg/jocl/cl_event;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clEnqueueCopyImageNative
  (JNIEnv *, jclass, jobject, jobject, jobject, jlongArray, jlongArray, jlongArray, jint, jobjectArray, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueCopyImageToBufferNative
 * Signature: (Lorg/jocl/cl_command_queue;Lorg/jocl/cl_mem;Lorg/jocl/cl_mem;[J[JJI[Lorg/jocl/cl_event;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clEnqueueCopyImageToBufferNative
  (JNIEnv *, jclass, jobject, jobject, jobject, jlongArray, jlongArray, jlong, jint, jobjectArray, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueCopyBufferToImageNative
 * Signature: (Lorg/jocl/cl_command_queue;Lorg/jocl/cl_mem;Lorg/jocl/cl_mem;J[J[JI[Lorg/jocl/cl_event;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clEnqueueCopyBufferToImageNative
  (JNIEnv *, jclass, jobject, jobject, jobject, jlong, jlongArray, jlongArray, jint, jobjectArray, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueMapBufferNative
 * Signature: (Lorg/jocl/cl_command_queue;Lorg/jocl/cl_mem;ZJJJI[Lorg/jocl/cl_event;Lorg/jocl/cl_event;[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_jocl_CL_clEnqueueMapBufferNative
  (JNIEnv *, jclass, jobject, jobject, jboolean, jlong, jlong, jlong, jint, jobjectArray, jobject, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueMapImageNative
 * Signature: (Lorg/jocl/cl_command_queue;Lorg/jocl/cl_mem;ZJ[J[J[J[JI[Lorg/jocl/cl_event;Lorg/jocl/cl_event;[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_jocl_CL_clEnqueueMapImageNative
  (JNIEnv *, jclass, jobject, jobject, jboolean, jlong, jlongArray, jlongArray, jlongArray, jlongArray, jint, jobjectArray, jobject, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueUnmapMemObjectNative
 * Signature: (Lorg/jocl/cl_command_queue;Lorg/jocl/cl_mem;Ljava/nio/ByteBuffer;I[Lorg/jocl/cl_event;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clEnqueueUnmapMemObjectNative
  (JNIEnv *, jclass, jobject, jobject, jobject, jint, jobjectArray, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueNDRangeKernelNative
 * Signature: (Lorg/jocl/cl_command_queue;Lorg/jocl/cl_kernel;I[J[J[JI[Lorg/jocl/cl_event;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clEnqueueNDRangeKernelNative
  (JNIEnv *, jclass, jobject, jobject, jint, jlongArray, jlongArray, jlongArray, jint, jobjectArray, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueTaskNative
 * Signature: (Lorg/jocl/cl_command_queue;Lorg/jocl/cl_kernel;I[Lorg/jocl/cl_event;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clEnqueueTaskNative
  (JNIEnv *, jclass, jobject, jobject, jint, jobjectArray, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueNativeKernelNative
 * Signature: (Lorg/jocl/cl_command_queue;Lorg/jocl/EnqueueNativeKernelFunction;Ljava/lang/Object;JI[Lorg/jocl/cl_mem;[Lorg/jocl/Pointer;I[Lorg/jocl/cl_event;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clEnqueueNativeKernelNative
  (JNIEnv *, jclass, jobject, jobject, jobject, jlong, jint, jobjectArray, jobjectArray, jint, jobjectArray, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueMarkerNative
 * Signature: (Lorg/jocl/cl_command_queue;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clEnqueueMarkerNative
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueWaitForEventsNative
 * Signature: (Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clEnqueueWaitForEventsNative
  (JNIEnv *, jclass, jobject, jint, jobjectArray);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueBarrierNative
 * Signature: (Lorg/jocl/cl_command_queue;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clEnqueueBarrierNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clCreateFromGLBufferNative
 * Signature: (Lorg/jocl/cl_context;JI[I)Lorg/jocl/cl_mem;
 */
JNIEXPORT jobject JNICALL Java_org_jocl_CL_clCreateFromGLBufferNative
  (JNIEnv *, jclass, jobject, jlong, jint, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clCreateFromGLTexture2DNative
 * Signature: (Lorg/jocl/cl_context;JIII[I)Lorg/jocl/cl_mem;
 */
JNIEXPORT jobject JNICALL Java_org_jocl_CL_clCreateFromGLTexture2DNative
  (JNIEnv *, jclass, jobject, jlong, jint, jint, jint, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clCreateFromGLTexture3DNative
 * Signature: (Lorg/jocl/cl_context;JIII[I)Lorg/jocl/cl_mem;
 */
JNIEXPORT jobject JNICALL Java_org_jocl_CL_clCreateFromGLTexture3DNative
  (JNIEnv *, jclass, jobject, jlong, jint, jint, jint, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clCreateFromGLRenderbufferNative
 * Signature: (Lorg/jocl/cl_context;JI[I)Lorg/jocl/cl_mem;
 */
JNIEXPORT jobject JNICALL Java_org_jocl_CL_clCreateFromGLRenderbufferNative
  (JNIEnv *, jclass, jobject, jlong, jint, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clGetGLObjectInfoNative
 * Signature: (Lorg/jocl/cl_mem;[I[I)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clGetGLObjectInfoNative
  (JNIEnv *, jclass, jobject, jintArray, jintArray);

/*
 * Class:     org_jocl_CL
 * Method:    clGetGLTextureInfoNative
 * Signature: (Lorg/jocl/cl_mem;IJLorg/jocl/Pointer;[J)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clGetGLTextureInfoNative
  (JNIEnv *, jclass, jobject, jint, jlong, jobject, jlongArray);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueAcquireGLObjectsNative
 * Signature: (Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_mem;I[Lorg/jocl/cl_event;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clEnqueueAcquireGLObjectsNative
  (JNIEnv *, jclass, jobject, jint, jobjectArray, jint, jobjectArray, jobject);

/*
 * Class:     org_jocl_CL
 * Method:    clEnqueueReleaseGLObjectsNative
 * Signature: (Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_mem;I[Lorg/jocl/cl_event;Lorg/jocl/cl_event;)I
 */
JNIEXPORT jint JNICALL Java_org_jocl_CL_clEnqueueReleaseGLObjectsNative
  (JNIEnv *, jclass, jobject, jint, jobjectArray, jint, jobjectArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
